### ISSUE TITLE
Confirmation Email - Not Working

### ISSUE THREAD

**Issue by Jahannie** [SoPR/horas#134]
When a new account is created, the confirmation email is not received. Although the accounts are created, an error is displayed.

![image](https://user-images.githubusercontent.com/14282888/107785781-64f51b80-6d23-11eb-91ca-7f4da9f08630.png)

**Comment by froi** [comment]
This error has been corrected. There was a misconfiguration with the service that was being used to send emails. Accounts can now be created.
