### ISSUE TITLE
Sign Up errors - Facebook, Twitter, Google

### ISSUE THREAD

**Issue by Jahannie** [SoPR/horas#135]
User can't create new account through social media plugins

Twitter
![image (5)](https://user-images.githubusercontent.com/14282888/107786193-f06eac80-6d23-11eb-9a5d-698b420ebf91.png)

Google
![image (4)](https://user-images.githubusercontent.com/14282888/107786194-f06eac80-6d23-11eb-8d88-3de0c19684f0.png)

Facebook
![image (3)](https://user-images.githubusercontent.com/14282888/107786195-f1074300-6d23-11eb-84ec-2783cf45cdc3.png)

**Comment by gcollazo** [comment]
Removing social logins
