### ISSUE TITLE
Rename protege

### ISSUE THREAD

**Issue by gcollazo** [SoPR/horas#77]
I would like to suggest a naming change from protege to apprentice.

Mentor <> Apprentice

Thoughts?

**Comment by froi** [comment]
I would use mentee. I think it's also the correct term for what the project does.

The logic goes:
* Mentor => mentee
* Master => apprentice
* Teacher => student

**Comment by gcollazo** [comment]
IMHO apprentice is a more approachable, and helps me set my expectations. "I'm going to be an apprentice".

> The person in receipt of mentorship may be referred to as a protégé (male), a protégée (female), an **apprentice** or, in the 2000s, a mentee.
https://en.m.wikipedia.org/wiki/Mentorship

**Comment by froi** [comment]
Wouldn't the term apprentice set the expectation that you will be more of a student and that you will be paired to a single person?

I would hate for people to read that and think that they are going to receive a free class and be disappointed

I'm going to do some user research about this and get back to you what I find. Deal?

**Comment by ajRiverav** [comment]
I like apprentice, too, but in the context of the website, mentee seems to be the right word. 

Apprentice comes across as if you are going to learn a skill, whereas mentee is more about receiving mentorship.

**Comment by froi** [comment]
So I've talked talked to a couple of people, one of them a team member that was an apprentice electrician, and he mentioned the following: "When you mention to somebody apprentice or apprenticeship the expectation is that this relationship will be a multi year one. I was an apprentice electrician and after three years with the master electrician I moved on to journeyman."

I'll keep asking and I'll start recording responses.
