### ISSUE TITLE
Remove Brunch setup for something better

### ISSUE THREAD

**Issue by froi** [SoPR/horas#84]
The brunch setup is kind of old and janky. We would like to change it to something more modern/easier/better. @jpadilla suggests webpack, but honestly I have no preference.

I would also no treat our static files as a app as it's handled now (maybe I'm wrong).

**Comment by gcollazo** [comment]
@froi que branch debería usar como punto de partida? mater?

**Comment by froi** [comment]
Master.

**Comment by gcollazo** [comment]
Thanks
