### ISSUE TITLE
Change Heroku dynos to not be legacy

### ISSUE THREAD

**Issue by froi** [SoPR/horas#93]
We want to add pipelines to the project but we can't using the current legacy dynos.

- [x] Change legacy dynos
![image](https://cloud.githubusercontent.com/assets/1918027/26511376/bfae6f86-422f-11e7-92e4-10e7d1b8f748.png)
- [ ] Connect app to Github repo.

**Comment by froi** [comment]
@gcollazo Any possibility on you working on this or should I just close it for now?

**Comment by rnegron** [comment]
This would be cool. Setting up pipelines required admin rights...cc @gcollazo

**Comment by froi** [comment]
Hey peeps. I'm closing this out since there's no real movement at the moment. Thanks! 😉
