### ISSUE TITLE
Facebook API deprecation

### ISSUE THREAD

**Issue by gcollazo** [SoPR/horas#99]
![img_0048](https://user-images.githubusercontent.com/61048/27064882-b2562572-4fc7-11e7-9005-ce5233efb0c3.PNG)

**Comment by froi** [comment]
@gcollazo Can you handle this? I don't have access to the app dashboard.

**Comment by jpadilla** [comment]
Nothing we need to do here. django-allauth is using v2.4 of the sdk. @froi I was going to deploy 0bc42a1 but seems like heroku/github are not in sync, can you check if you've pushed everything to this repo?
